### ISSUE TITLE
Extra double-nesting, galaxy.yml in wrong place

### ISSUE THREAD

**Issue by AlanCoding** [ansible/content_collector#16]
My testing is consistent with the file structure given in the example, but the example does not mention where `galaxy.yml` goes. I find that it is here:

```
my_ansible_collection
├── galaxy.yml
└── contoso
    └── myos
        ├── docs
        ├── playbooks
        ├── plugins
        │   ├── action
        │   ├── filter
        │   ├── inventory
        │   ├── modules
        │   │   ├── __init__.py
        │   │   ├── myos_module1.py
        │   │   ├── myos_module2.py
        │   │   └── myos_module3.py
        │   └── module_utils
        │       └── network
        │           └── myos
        │               ├── __init__.py
        │               └── myos.py
        └── roles
```

If I cd into `my_ansible_collection`, installing this does not seem to work.

It should not be in the folder `my_ansible_collection`, but instead in the `myos`, assuming that the `ansible-galaxy collection install` command is ran from the `myos` folder.

In my case, I'm using the tower modules, so I start by exporting it via this tool., `site.yml`:

```yaml
- hosts: localhost
  gather_facts: false
  vars:
    ansible_source_directory: ./ansible
    destination_directory: ~/tower_modules
    collection_namespace: awx
    collection_name: awx
    source_sub_directory: /web_infrastructure/ansible_tower
  roles:
  - scaffold_directories
  - migrate_content
  - test_modules
  - galaxy_yml
```

Then I run `ansible-playbook site.yaml`

#### Example steps that install incorrectly

```
ansible-galaxy collection build --output-path=~/Documents/repos/utility-playbooks/test_build_bad
ansible-galaxy collection install ~/Documents/repos/utility-playbooks/test_build_bad/awx-awx-1.0.0.tar.gz -p ~/Documents/repos/utility-playbooks/test_install_bad
# (in utility playbooks)
ANSIBLE_COLLECTIONS_PATHS=$(pwd)/test_install_bad/ ansible-playbook -i localhost, -e ansible_python_interpreter=~/.virtualenvs/cli/bin/python tower_module.yml
```

This does not use the exported collection, but instead uses the modules as it already exists in Ansible.

Note location of modules, that's a little too many folders

```
test_install_bad/ansible_collections/awx/awx/awx/awx/plugins/modules/tower_organization.py
```

#### Example steps that install correctly

```
cd tower_modules/awx/awx/
cp ../../galaxy.yml galaxy.yml
ansible-galaxy collection build --output-path=~/Documents/repos/utility-playbooks/test_build
ansible-galaxy collection install ~/Documents/repos/utility-playbooks/test_build/awx-awx-1.0.0.tar.gz -p ~/Documents/repos/utility-playbooks/test_install
ANSIBLE_COLLECTIONS_PATHS=$(pwd)/test_install/ ansible-playbook -i localhost, -e ansible_python_interpreter=~/.virtualenvs/cli/bin/python tower_module.yml
```

Location of modules here

```
test_install/ansible_collections/awx/awx/plugins/modules/tower_organization.py
```

So my conclusion is that something is wrong with where this tool is putting things.

**Comment by geerlingguy** [comment]
I just tested this with the vars:

```
  vars:
    ansible_source_directory: ./ansible-2.9.4
    destination_directory: ~/Downloads/kubecollect
    collection_namespace: community
    collection_name: kubernetes
    collection_description: Kubernetes Collection for Ansible
    source_sub_directory: /clustering/k8s
```

And ended up getting the `galaxy.yml` file two directory levels up from where it should be. It was placed in `~/Downloads/kubecollect/galaxy.yml` instead of `~/Downloads/kubecollect/community/kubernetes/galaxy.yml`.

Related: https://github.com/ansible-collections/kubernetes/issues/1
